export default {
    maxLevel: 5,
    bossLifes: 4,
    LEVEL_1: {
        SKILL_COUNT: 10,
        SKILL_EXPERIENCE: 100,
        CERTIFICATION_COUNT: 0,
        CERTIFICATION_EXPERIENCE: 0,
        ULTIMATE_EXPERIENCE: 0,
        PLAYER_HEALTH: 100,
        PLAYER_EXPERIENCE: 1000,
        DAMAGE: {
            SKILL: 0,
            CERTIFICATION: 100,
            ULTIMATE: 450,
            HEALTH_ELIXIR: 0,
            BOSSWALLSMALL: 2000,
            BOSSWALLBIG: 4000,
            BOSS: 5000,
        },
    },
    LEVEL_2: {
        SKILL_COUNT: 25,
        SKILL_EXPERIENCE: 100,
        CERTIFICATION_COUNT: 0,
        CERTIFICATION_EXPERIENCE: 0,
        ULTIMATE_EXPERIENCE: 0,
        PLAYER_HEALTH: 500,
        PLAYER_EXPERIENCE: 2500,
        DAMAGE: {
            SKILL: 0,
            CERTIFICATION: 0,
            ULTIMATE: 400,
            HEALTH_ELIXIR: 0,
            BOSSWALLSMALL: 2000,
            BOSSWALLBIG: 4000,
            BOSS: 5000,
        },
    },
    LEVEL_3: {
        SKILL_COUNT: 0,
        SKILL_EXPERIENCE: 100,
        CERTIFICATION_COUNT: 5,
        CERTIFICATION_EXPERIENCE: 500,
        ULTIMATE_COUNT: 0,
        ULTIMATE_EXPERIENCE: 0,
        PLAYER_HEALTH: 1000,
        PLAYER_EXPERIENCE: 5000,
        DAMAGE: {
            SKILL: 0,
            CERTIFICATION: 0,
            ULTIMATE: 200,
            HEALTH_ELIXIR: 0,
            BOSSWALLSMALL: 2000,
            BOSSWALLBIG: 4000,
            BOSS: 5000,
        },
    },
    LEVEL_4: {
        SKILL_COUNT: 0,
        SKILL_EXPERIENCE: 100,
        CERTIFICATION_COUNT: 0,
        CERTIFICATION_EXPERIENCE: 500,
        ULTIMATE_COUNT: 3,
        ULTIMATE_EXPERIENCE: 1500,
        HEALTH_ELIXIR: 0,
        PLAYER_HEALTH: 2000,
        PLAYER_EXPERIENCE: 9500,
        DAMAGE: {
            SKILL: 0,
            CERTIFICATION: 0,
            ULTIMATE: 0,
            HEALTH_ELIXIR: 0,
            BOSSWALLSMALL: 1500,
            BOSSWALLBIG: 2000,
            BOSS: 5000,
        },

    },
    LEVEL_5: {
        SKILL_COUNT: 0,
        SKILL_EXPERIENCE: 100,
        CERTIFICATION_COUNT: 0,
        CERTIFICATION_EXPERIENCE: 500,
        ULTIMATE_COUNT: 0,
        ULTIMATE_EXPERIENCE: 1500,
        HEALTH_ELIXIR: 1000,
        PLAYER_HEALTH: 4000,
        PLAYER_EXPERIENCE: 9500,
        DAMAGE: {
            SKILL: 0,
            CERTIFICATION: 0,
            ULTIMATE: 0,
            HEALTH_ELIXIR: 0,
            BOSSWALLSMALL: 1000,
            BOSSWALLBIG: 2000,
            BOSS: 500,
        },
    },
};